name: Test

on: 
  workflow_dispatch:
  pull_request:
  push:
    branches: master

jobs:
  test:
    runs-on: ubuntu-latest
    name: HTML Preview
    steps:
      - uses: actions/checkout@v4
      - name: Get HTML preview link
        id: html_preview
        uses: ./ # NOTE: replace with the latest version of this Action
        with:
          html_file: ./index.html
